<?php
/**
 * Run Installation
 */

header('Content-Type: application/json');

// Only allow POST requests
if ($_SERVER['REQUEST_METHOD'] !== 'POST') {
    echo json_encode(['success' => false, 'message' => 'Invalid request method']);
    exit;
}

// Check if already installed
if (file_exists(__DIR__ . '/installed.lock')) {
    echo json_encode(['success' => false, 'message' => 'System is already installed']);
    exit;
}

// Get all form data
$appName = trim($_POST['app_name'] ?? 'CheckTrack');
$appUrl = trim($_POST['app_url'] ?? '');
$lang = $_POST['lang'] ?? 'en';
$timezone = trim($_POST['timezone'] ?? 'Europe/Rome');

$dbHost = trim($_POST['db_host'] ?? 'localhost');
$dbName = trim($_POST['db_name'] ?? '');
$dbUser = trim($_POST['db_user'] ?? '');
$dbPass = $_POST['db_pass'] ?? '';

$adminName = trim($_POST['admin_name'] ?? '');
$adminUser = trim($_POST['admin_user'] ?? '');
$adminPass = $_POST['admin_pass'] ?? '';

$devName = trim($_POST['dev_name'] ?? 'Md Minhaz Bin Santo');
$devCompany = trim($_POST['dev_company'] ?? 'Beenet IT Solutions');
$devWebsite = trim($_POST['dev_website'] ?? 'https://minhazbinsanto.com');
$devEmail = trim($_POST['dev_email'] ?? 'contact@minhazbinsanto.com');
$showDevFooter = isset($_POST['show_dev_footer']) ? true : false;

// Validate required fields
$errors = [];

if (empty($appName)) $errors[] = 'Application name is required';
if (empty($appUrl)) $errors[] = 'Application URL is required';
if (empty($dbName)) $errors[] = 'Database name is required';
if (empty($dbUser)) $errors[] = 'Database username is required';
if (empty($adminName)) $errors[] = 'Admin name is required';
if (empty($adminUser)) $errors[] = 'Admin username is required';
if (strlen($adminPass) < 6) $errors[] = 'Admin password must be at least 6 characters';

// Validate timezone
if (!in_array($timezone, DateTimeZone::listIdentifiers())) {
    $timezone = 'Europe/Rome';
}

if (!empty($errors)) {
    echo json_encode(['success' => false, 'message' => implode(', ', $errors)]);
    exit;
}

// Progress tracking
$progress = [];
$progress[] = ['step' => 1, 'message' => 'Testing database connection...'];

// Test database connection
try {
    $dsn = "mysql:host={$dbHost};charset=utf8mb4";
    $pdo = new PDO($dsn, $dbUser, $dbPass, [
        PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION
    ]);

    // Create database if not exists
    $pdo->exec("CREATE DATABASE IF NOT EXISTS `{$dbName}` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci");
    $pdo->exec("USE `{$dbName}`");

} catch (PDOException $e) {
    echo json_encode(['success' => false, 'message' => 'Database connection failed: ' . $e->getMessage()]);
    exit;
}

$progress[] = ['step' => 2, 'message' => 'Creating configuration file...'];

// Create config.php
$configContent = <<<'PHP'
<?php
/**
 * Application Configuration
 * Generated by CheckTrack Installer
 */

// Database credentials
define('DB_HOST', '{$dbHost}');
define('DB_NAME', '{$dbName}');
define('DB_USER', '{$dbUser}');
define('DB_PASS', '{$dbPass}');

// Google Apps Script Webhook URL
define('GOOGLE_SCRIPT_WEBHOOK_URL', 'https://script.google.com/macros/s/YOUR_SCRIPT_ID/exec');

// Site URL
define('SITE_URL', '{$appUrl}');

// Session timeout in seconds (30 minutes)
define('SESSION_TIMEOUT', 1800);

// Application name
define('APP_NAME', '{$appName}');

// Default language
define('DEFAULT_LANG', '{$lang}');

// Default Timezone
define('DEFAULT_TIMEZONE', '{$timezone}');
date_default_timezone_set(DEFAULT_TIMEZONE);

// Developer Information
define('DEV_NAME', '{$devName}');
define('DEV_COMPANY', '{$devCompany}');
define('DEV_WEBSITE', '{$devWebsite}');
define('DEV_EMAIL', '{$devEmail}');
define('SHOW_DEV_FOOTER', {$showDevFooter});

// Google Sheets Webhook Secret
define('SHEETS_SECRET', 'checktrack-secret-2026');
PHP;

// Replace placeholders
$configContent = str_replace(
    ['{$dbHost}', '{$dbName}', '{$dbUser}', '{$dbPass}', '{$appUrl}', '{$appName}', '{$lang}', '{$timezone}', '{$devName}', '{$devCompany}', '{$devWebsite}', '{$devEmail}', '{$showDevFooter}'],
    [$dbHost, $dbName, $dbUser, $dbPass, $appUrl, $appName, $lang, $timezone, $devName, $devCompany, $devWebsite, $devEmail, $showDevFooter ? 'true' : 'false'],
    $configContent
);

$configFile = dirname(__DIR__) . '/config.php';
if (file_put_contents($configFile, $configContent) === false) {
    echo json_encode(['success' => false, 'message' => 'Failed to create config.php. Check file permissions.']);
    exit;
}

$progress[] = ['step' => 3, 'message' => 'Creating database tables...'];

// Read and execute SQL
$sqlFile = __DIR__ . '/../database.sql';
if (!file_exists($sqlFile)) {
    echo json_encode(['success' => false, 'message' => 'database.sql not found']);
    exit;
}

$sql = file_get_contents($sqlFile);

// Remove comments and split into statements
$sql = preg_replace('/--.*$/m', '', $sql);
$statements = array_filter(array_map('trim', explode(';', $sql)));

foreach ($statements as $statement) {
    if (!empty($statement)) {
        try {
            $pdo->exec($statement);
        } catch (PDOException $e) {
            // Skip if table already exists
            if ($e->getCode() != '42S01') {
                echo json_encode(['success' => false, 'message' => 'SQL Error: ' . $e->getMessage()]);
                exit;
            }
        }
    }
}

$progress[] = ['step' => 4, 'message' => 'Creating admin account...'];

// Create admin user with bcrypt password
$hashedPassword = password_hash($adminPass, PASSWORD_BCRYPT);
$stmt = $pdo->prepare("INSERT INTO users (name, username, password, role, lang, timezone, status) VALUES (?, ?, ?, 'admin', ?, ?, 1)");
$stmt->execute([$adminName, $adminUser, $hashedPassword, $lang, $timezone]);

$progress[] = ['step' => 5, 'message' => 'Finalizing installation...'];

// Create installed.lock file
$lockFile = __DIR__ . '/installed.lock';
$lockContent = json_encode([
    'installed_at' => date('Y-m-d H:i:s'),
    'version' => '1.0.0',
    'installed_by' => $adminUser
], JSON_PRETTY_PRINT);

if (file_put_contents($lockFile, $lockContent) === false) {
    echo json_encode(['success' => false, 'message' => 'Failed to create installed.lock. Check folder permissions.']);
    exit;
}

// Return success with progress
echo json_encode([
    'success' => true,
    'message' => 'Installation completed successfully!',
    'progress' => $progress
]);
